repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.77.1
    hooks:
        - id: terraform_fmt
          args:
            - --args=-recursive

        - id: terraform_tfsec
          args:
            - --args=--config-file=./.tfsec-config.yml --run-statistics

        - id: terraform_docs
          args:
            - --args=--config=.tfdocs-config.yaml --output-file=README.md

  # - repo: local
  #   hooks:
  #     - id: copy-md-files
  #       name: Copy and Rename README Files
  #       entry: |
  #         bash -c '
  #           for readme in modules/azure/*/README.md; do
  #             folder_name=$(basename $(dirname "$readme"))
  #             cp "$readme" "docs/${folder_name}.md"
  #           done
  #         '
  #       language: system
  #       pass_filenames: false

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-symlinks
      - id: check-merge-conflict
      - id: detect-private-key
