edit_uri: edit/main/docs/
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
repo_name: terraform-modules
repo_url: https://github.com/unique-ag/terraform-modules
site_dir: build
site_name: Terraform Modules
site_url: https://unique-ag.github.io/terraform-modules
theme:
  features:
    - content.action.edit
  favicon: https://www.unique.ch/hubfs/unique_assets/favicon/glyph_caumasee.svg
  logo:
    icon: assets/images/unique-logo.png
    href: https://www.unique.ch
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github
  name: material
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
