site_name: Terraform Modules
site_url: https://unique-ag.github.io/terraform-modules
site_dir: build
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - content.action.edit
  favicon: https://www.unique.ch/hubfs/unique_assets/favicon/glyph_caumasee.svg
  logo:
    icon: assets/images/unique-logo.png
    href: https://www.unique.ch
  font:
    text: Roboto
    code: Roboto Mono
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

repo_url: https://github.com/unique-ag/terraform-modules
repo_name: terraform-modules
edit_uri: edit/main/docs/
