name: "Release Azure Log Analytics Workspace"

on:
  workflow_dispatch: # allow manual runs for missed release workflow updates
  push:
    branches:
      - main
    paths:
      - modules/azure-log-analytics-workspace/module.yaml
  pull_request:
    branches:
      - main
    paths:
      - modules/azure-log-analytics-workspace/**

jobs:
  validate:
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/immutable-artifact.yaml
    with:
      module: azure-log-analytics-workspace

  release:
    if: ${{ github.event.ref == 'refs/heads/main' }}
    uses: ./.github/workflows/release.yaml
    with:
      module: azure-log-analytics-workspace
