name: "Release Azure PostgreSQL"

on:
  workflow_dispatch: # we allow manual runs as there are edge cases todo so (e.g. missed updating only the GitHub workflow or similar)
  push:
    branches:
      - main
    paths:
      - modules/azure-postgresql/module.yaml

jobs:
  release:
    uses: ./.github/workflows/release.yaml
    with:
      module: azure-postgresql
