name: 'TF-Azure'

on:
  push:
    branches: [ "main" ]
    paths:
      - "modules/azure/**"
  pull_request:
    paths:
      - "modules/azure/**"

permissions:
  contents: read

env:
  TF_DIR: modules/azure


jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        module: [resource-group]

    steps:
    - uses: actions/checkout@v3

    - name: Terraform Init
      run: |
        terraform -chdir=$TF_DIR init

    - name: Terraform Format check
      run: terraform -chdir=$TF_DIR/$MODULE_NAME/example fmt -check
      env:
        MODULE_NAME: ${{ matrix.module }}

    - name: Terraform Plan
      run: terraform -chdir=$TF_DIR/$MODULE_NAME/example plan -out=plan.out && terraform -chdir=$TF_DIR/$MODULE_NAME/example show -json plan.out > $TF_DIR/$MODULE_NAME/example/plan.out.json
      env:
        MODULE_NAME: ${{ matrix.module }}

    - name: Terraform security
      uses: aquasecurity/tfsec-action@v1.0.0
      env:
        MODULE_NAME: ${{ matrix.module }}

    - name: Terraform compliance
      uses: terraform-compliance/github_action@main
      with:
        plan: $TF_DIR/$MODULE_NAME/example/plan.out.json
        features: ./compliances
      env:
        MODULE_NAME: ${{ matrix.module }}
