name: "[terraform] Report Trivy Results"
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    paths:
      - modules/**/*.tf
      - .github/workflows/trivy.yaml
      - .github/configs/**
      - scripts/**

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Report
        run: ./scripts/trivy.sh trivy.sarif

      - name: Upload Sarif results
        uses: github/codeql-action/upload-sarif@6bb031afdd8eb862ea3fc1848194185e076637e5 #v3.28.11
        with:
          sarif_file: trivy.sarif
